let activities=[
  {
    id: 01,
    title: "Gymnastics",
    location: "Gym 02",
    price: 900,
    spaces: 5,
    image: "images/gymnastics.png",
    rating: 3,
  },
  {
    id: 02,
    title: "Dance",
    location: "Hall 03",
    price: 1000,
    spaces: 5,
    image: "images/dance.png",
    rating: 3,
  },
  {
    id: 03,
    title: "Cooking",
    location: "Classroom 101",
    price: 250,
    spaces: 5,
    image: "images/cooking.png",
    rating: 4,
    },
    {
      id: 04,
      title: "music",
      location: "Hall 02",
      price: 430,
      spaces: 5,
      image: "images/music.png",
      rating: 2,
    },
    {
      id: 05,
      title: "Painting",
      location: "Classroom 05",
      price: 150,
      spaces: 5,
      image: "images/painting.png",
      rating: 2,
    },
    {
      id: 06,
      title: "Photography",
      location: "Hall 04",
      price: 530,
      spaces: 5,
      image: "images/photography.png",
      rating: 4,
      },
      {
        id: 07,
        title: "Robotics",
        location: "Classroom 07",
        price: 880,
        spaces: 5,
        image: "images/robotics.png",
        rating: 4,
      },
      {
        id: 08,
        title: "Entrepreneurship",
        location: "UAE",
        price: 400,
        spaces: 5,
        image: "images/entrepreneurship.png",
        rating: 3,
      },
      {
        id: 09,
        title: "Swimming",
        location: "Swimming Pool",
        price: 570,
        spaces: 5,
        image: "images/swimming.png",
        rating: 4,
        },
        {
          id: 10,
          title: "Gardening",
          location: "School's Backyard",
          price: 330,
          spaces: 5,
          image: "images/gardening.png",
          rating: 1,
        },
]